## dataframe创建、属性、访问、方法

### 通过series创建

In [2]:
import pandas as pd
import numpy as np
s1=pd.Series([1,2,3,4,5,6])
s2=pd.Series([7,8,9,10,11,12])
df=pd.DataFrame({'第一列':s1,'第二列':s2})
df

   第一列  第二列
0    1    7
1    2    8
2    3    9
3    4   10
4    5   11
5    6   12

### 通过字典创建

In [3]:
df=pd.DataFrame({'id':[1,2,3,4,5,],'name':['clq','pll','dandi','huang','hou'],'age':[18,19,20,21,22],'score':[150,149,148,147,149]})
df

   id   name  age  score
0   1    clq   18    150
1   2    pll   19    149
2   3  dandi   20    148
3   4  huang   21    147
4   5    hou   22    149